language: ruby
cache: bundler

rvm:
  - 1.9.3
branches:
  only:
    - deploy

before_install:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval 'ssh-agent -s'
  - ssh-add
  - git config user.email "build@travisci.org"
  - git config user.email "Travis CI"

script:
    - bundle exec jekyll build
    - bundle exec octopress deploy
