language: ruby
cache: bundler

rvm:
  - 2.2.0
branches:
  only:
    - deploy

before_install:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "$GITHUB_PRIVATE_KEY" > ~/.ssh/travis_rsa
  - chmod 600 ~/.ssh/travis_rsa
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/travis_rsa
  - git config user.email "build@travisci.org"
  - git config user.email "Travis CI"

script:
    - bundle exec jekyll build
    - bundle exec octopress deploy
